// Generated by https://quicktype.io

export interface Categories {
    api_warning: string;
    body:        Body[];
}

export interface Category {
    id:                number;
    title:             string;
    description:       null | string;
    parent_id:         number | null;
    region_id:         number;
    updated_at:        string;
    priority:          number;
    gradient:          Gradient;
    banner_image_url?: string;
    banner_image?:     BannerImage;
}

export interface BannerImage {
    original: string;
}

export interface Gradient {
    start: string;
    end:   string;
}
