// Generated by https://quicktype.io

export interface Popular {
    window:      number;
    version:     number;
    timestamp:   number;
    api_warning: string;
    body:        Body;
}

export interface Body {
    totals:      Totals;
    audio_clips: AudioClipPopular[];
}

export interface AudioClipPopular {
    id:                    number;
    season_number:         null;
    episode_number:        null;
    title:                 string;
    description:           string;
    formatted_description: string;
    updated_at:            string;
    user:                  User;
    link_style:            LinkStyle;
    channel:               Channel;
    duration:              number;
    mp3_filesize:          number;
    uploaded_at:           string;
    recorded_at:           string;
    uploaded_at_ts:        number;
    recorded_at_ts:        number;
    can_comment:           boolean;
    can_embed:             boolean;
    category_id:           number;
    counts:                Counts;
    urls:                  AudioClipUrls;
}

export interface Channel {
    id:    number;
    title: Title;
    urls:  ChannelUrls;
}

export enum Title {
    MorbidATrueCrimePodcast = "Morbid: A True Crime Podcast",
}

export interface ChannelUrls {
    detail:     string;
    logo_image: Image;
}

export interface Image {
    original: string;
}

export interface Counts {
    comments: number;
    likes:    number;
    plays:    number;
}

export enum LinkStyle {
    Channel = "channel",
}

export interface AudioClipUrls {
    detail:   string;
    high_mp3: string;
    wave_img: string;
}

export interface User {
    id:       number;
    username: null;
    urls:     UserUrls;
}

export interface UserUrls {
    profile:       string;
    image:         string;
    profile_image: Image;
}

export interface Totals {
    count:  number;
    offset: number;
}
